# Generated by Django 5.0.6 on 2024-07-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('secure_acceptance_status', models.CharField(blank=True, max_length=100)),
                ('has_sa_keys', models.BooleanField(default=False)),
                ('has_p12_keys', models.BooleanField(default=False)),
                ('has_soap_keys', models.BooleanField(default=False)),
                ('has_scmp_keys', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
