# Generated by Django 5.0.6 on 2024-08-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITReportInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='access_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='additional_information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchant',
            name='billing_information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchant',
            name='confirmation_settings',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pricing_information',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='merchant',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
