# Generated by Django 5.0.6 on 2024-08-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITReportInterface', '0002_merchant_access_key_merchant_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='disable_captcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(default='default_merchant_id', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='orderpage_transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('authorization', 'Authorization')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='test_mode',
            field=models.BooleanField(choices=[(True, 'Submit Orders to the Cybersource test system. This is the default setting for the shopmit development and test servers'), (False, 'Submit Orders to the Cybersource production system. This is the default setting for the shopmit production server')], default=True),
        ),
    ]
