# Generated by Django 5.0.6 on 2024-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITReportInterface', '0003_merchant_disable_captcha_merchant_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(default='default_merchant_id', max_length=100, unique=True),
        ),
    ]
