# Generated by Django 5.0.6 on 2024-08-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITReportInterface', '0004_alter_merchant_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='test_mode',
            field=models.BooleanField(choices=[(True, 'Submit Orders to the Cybersource test system.'), (False, 'Submit Orders to the Cybersource production system.')], default=True),
        ),
    ]
